Fix undefined reference to constexpr with GCC
Use a variable due to https://en.cppreference.com/w/cpp/language/definition#ODR-use
Otherwise it doesn't compile with GCC ("undefined reference to")